version: 2

models:
    - name: dbt_retention_agent_targets
      description: "Transform Retention Agent Targets Google Sheet"
      config:
          enabled: true
          tags: google_sheets_ret_agent_targets
    - name: pool_targets_dbt
      description: "modify text to integer pool targets"
      config:
          enabled: true
          tags: pool_targets
    - name: country_targets_neil_dbt
      description: "modify text to integer for country targets neil"
      config:
          enabled: true
          tags: country_targets_neil