version: 2

models:
    - name: dbt_retention_agent_targets
      description: "Transform Retention Agent Targets Google Sheet"
      config:
          enabled: true
          tags: google_sheets_ret_agent_targets
    - name: pool_targets_dbt
      description: "modify text to integer pool targets"
      config:
          enabled: true
          tags: pool_targets
    - name: country_targets_neil_dbt
      description: "modify text to integer for country targets neil"
      config:
          enabled: true
          tags: country_targets_neil
    - name: country_pool_targets_dbt
      description: "modify text to integer for country pool targets"
      config:
          enabled: true
          tags: country_pool_targets
    - name: target_percent_server_dbt
      description: "model to calculate targets percents"
      config:
          enabled: true
          tags: target_percent_dbt
    - name: agent_name_benjamin_dbt
      description: "transform benjamin reports"
      config:
          enabled: true
          tags: agent_name_benjamin
    - name: agent_name_adam_dbt
      description: "transform adam reports"
      config:
          enabled: true
          tags: agent_name_adam
    - name: last_refreshed_datetime_dbt
      description: "last refreshed datetime"
      config:
          enabled: true
          tags: last_refreshed_dbt